nodeLinker: node-modules
packageExtensions:
    # awaiting fix: https://github.com/facebook/create-react-app/issues/11982
    'eslint-plugin-flowtype@*':
        peerDependenciesMeta:
            '@babel/plugin-syntax-flow':
                optional: true
            '@babel/plugin-transform-react-jsx':
                optional: true
    '@testing-library/user-event@*':
        peerDependenciesMeta:
            '@testing-library/dom':
                optional: true
