name: Pull requests

on:
    pull_request:
        branches: ['*']

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout code
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'

            - name: Install dependencies
              run: yarn install

            - name: Validate lint
              run: yarn lint

            - name: Test
              run: yarn test
